import { test, expect } from '@playwright/test'

test('preset slider supports keyboard selection and survives finish changes', async ({ page }) => {
  await page.goto('/?component=leather-background')
  await page.getByRole('button', { name: 'Colors', exact: true }).click()
  const panel = page.getByRole('region', { name: 'Leather colors' })
  const slider = panel.getByRole('slider', { name: 'Preset palette' })
  await expect(slider).toHaveValue('0')
  await expect(page.locator('.leather-background')).toHaveAttribute('data-palette', 'original')
  await slider.focus()
  await page.keyboard.press('ArrowRight')
  await expect(slider).toHaveAttribute('aria-valuetext', 'Cognac')
  await expect(panel.getByRole('textbox', { name: 'Pebbles hex' })).toHaveValue('#754328')
  await expect(panel.getByRole('textbox', { name: 'Crevices / edges hex' })).toHaveValue('#D4A579')
  await expect(page.locator('.leather-background')).toHaveAttribute('data-palette', 'custom')
  await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await expect(slider).toHaveValue('1')
  await expect(panel.getByRole('textbox', { name: 'Pebbles hex' })).toHaveValue('#754328')
  await page.getByRole('button', { name: 'Colors', exact: true }).click()
  await expect(panel).toBeHidden()
  await page.getByRole('button', { name: 'Colors', exact: true }).click()
  await expect(slider).toHaveAttribute('aria-valuetext', 'Cognac')
  for (const name of ['Oxblood', 'Forest', 'Navy', 'Graphite']) {
    await panel.getByRole('button', { name, exact: true }).click()
    await expect(slider).toHaveAttribute('aria-valuetext', name)
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('custom hex and color inputs preserve valid colors and reset cleanly', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/?component=leather-background&finish=dark')
  await page.getByRole('button', { name: 'Colors', exact: true }).click()
  const panel = page.getByRole('region', { name: 'Leather colors' })
  const pebble = panel.getByRole('textbox', { name: 'Pebbles hex' })
  const crevice = panel.getByRole('textbox', { name: 'Crevices / edges hex' })
  await pebble.fill('#123456')
  await expect(panel.locator('output')).toHaveText('Custom')
  await crevice.fill('abc')
  await crevice.press('Enter')
  await expect(crevice).toHaveValue('#AABBCC')
  await pebble.fill('#wrong')
  await expect(pebble).toHaveAttribute('aria-invalid', 'true')
  await pebble.press('Tab')
  await expect(pebble).toHaveValue('#123456')
  await panel.getByLabel('Pebbles color', { exact: true }).fill('#555555')
  await panel.getByLabel('Crevices / edges color', { exact: true }).fill('#555555')
  await expect(pebble).toHaveValue('#555555')
  await expect(crevice).toHaveValue('#555555')
  await expect(page.locator('.leather-background__relief')).toBeVisible()
  await page.getByRole('button', { name: 'Cream', exact: true }).click()
  await expect(pebble).toHaveValue('#555555')
  await panel.getByRole('button', { name: 'Reset to original' }).click()
  await expect(page.locator('.leather-background')).toHaveAttribute('data-palette', 'original')
  await expect(panel.locator('output')).toHaveText('Original')
  await expect(page.locator('.leather-background__filters')).toHaveCount(0)
  await expect(page.locator('.leather-background__relief')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('palette selection is scoped to the current preview session', async ({ page }) => {
  await page.goto('/?component=leather-background')
  await page.getByRole('button', { name: 'Colors', exact: true }).click()
  await page.getByRole('button', { name: 'Forest', exact: true }).click()
  await page.reload()
  await expect(page.locator('.leather-background')).toHaveAttribute('data-palette', 'original')
  await expect(page.getByRole('button', { name: 'Colors', exact: true })).toHaveAttribute('aria-expanded', 'false')
})
