import { test, expect, type Page } from '@playwright/test'
test.setTimeout(45000)
const host = (page: Page) => page.locator('.signature-moments')
async function load(page: Page) {
  await page.goto('/?component=signature-moments')
  await expect(host(page)).toHaveAttribute('data-ready', 'true')
}
async function go(page: Page, index = 0) {
  await host(page).evaluate((el, index) => window.scrollTo({ top: el.getBoundingClientRect().top + scrollY + Number(el.dataset.entranceDistance) + Number(el.dataset.step) * index, behavior: 'instant' }), index)
  await expect(host(page)).toHaveAttribute('data-phase', 'moments')
  await expect(host(page)).toHaveAttribute('data-current', String(index))
  await expect(host(page)).toHaveAttribute('data-motion', 'resting')
}
async function playing(page: Page) {
  await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).readyState >= 3 && !(v as HTMLVideoElement).paused)).toBe(true)
  const time = await page.locator('video').evaluate(v => (v as HTMLVideoElement).currentTime)
  await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).currentTime)).toBeGreaterThan(time)
}

test('entrance lands, scrolling reverses, and navigation stays inside the viewport', async ({ page }, info) => {
  const errors: string[] = [], external: string[] = [], clips: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => {
    if (request.url().startsWith('http') && !request.url().includes('127.0.0.1')) external.push(request.url())
    if (request.url().endsWith('.mp4')) clips.push(request.url())
  })
  await load(page)
  await expect(page.getByRole('button', { name: 'Explore signature moments' })).toBeVisible()
  await host(page).evaluate(el => window.scrollTo({ top: Number(el.dataset.entranceDistance) * .4, behavior: 'instant' }))
  await expect(page.locator('.signature-flight')).toBeVisible()
  const center = await page.locator('.signature-flight').boundingBox()
  expect(center!.width).toBeGreaterThan(80)
  await go(page, 2)
  await expect(page.locator('.signature-flight')).toBeHidden()
  const rect = await page.getByRole('button', { name: 'Open The Catch', exact: true }).boundingBox()
  expect(rect!.x).toBeGreaterThan(0)
  expect(rect!.x + rect!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await page.screenshot({ path: `artifacts/signature-validation/verified-field-${info.project.name}.png` })
  await page.getByRole('button', { name: 'Show moment 5 of 5' }).click()
  await expect(host(page)).toHaveAttribute('data-current', '4')
  await go(page, 0)
  await page.locator('.signature-pin').focus()
  await page.keyboard.press('ArrowRight')
  await expect(host(page)).toHaveAttribute('data-current', '1')
  await expect(page.getByRole('button', { name: 'Open Single Season Record' })).toBeFocused()
  await page.keyboard.press('End')
  await expect(host(page)).toHaveAttribute('data-current', '4')
  await page.keyboard.press('Home')
  await expect(host(page)).toHaveAttribute('data-current', '0')
  await host(page).evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await expect(page.getByRole('button', { name: 'Explore signature moments' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([]); expect(external).toEqual([]); expect(clips).toEqual([])
})

test('card flips into real playback, controls work, and closing restores focus and stops audio', async ({ page }, info) => {
  const errors: string[] = [], requested: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (request.url().endsWith('.mp4')) requested.push(request.url()) })
  await load(page); await go(page, 2)
  const card = page.getByRole('button', { name: 'Open The Catch', exact: true })
  await card.focus(); await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible()
  await playing(page)
  await page.waitForTimeout(850)
  const video = page.locator('video')
  const bounds = await video.boundingBox(), viewport = page.viewportSize()!
  expect(bounds!.x).toBeGreaterThanOrEqual(0); expect(bounds!.y).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width + 1)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(viewport.height + 1)
  expect(bounds!.width / bounds!.height).toBeCloseTo(16 / 9, 1)
  await page.getByRole('button', { name: 'Pause', exact: true }).click({ force: true })
  await expect.poll(() => video.evaluate(v => (v as HTMLVideoElement).paused)).toBe(true)
  await page.getByRole('slider', { name: 'Seek' }).fill('10')
  await expect.poll(() => video.evaluate(v => (v as HTMLVideoElement).currentTime)).toBeGreaterThanOrEqual(9.8)
  await page.getByRole('button', { name: 'Mute', exact: true }).click({ force: true })
  await expect.poll(() => video.evaluate(v => (v as HTMLVideoElement).muted)).toBe(true)
  await page.getByRole('button', { name: 'Unmute', exact: true }).click({ force: true })
  await page.getByRole('button', { name: 'Play', exact: true }).click({ force: true })
  await playing(page)
  await page.screenshot({ path: `artifacts/signature-validation/verified-player-${info.project.name}.png` })
  await page.getByRole('button', { name: 'Close video' }).focus()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'Enter fullscreen' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Close video' })).toBeFocused()
  await video.evaluate(v => { (window as unknown as { retiredVideo: HTMLVideoElement }).retiredVideo = v as HTMLVideoElement })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(await page.evaluate(() => (window as unknown as { retiredVideo: HTMLVideoElement }).retiredVideo.paused)).toBe(true)
  await expect(card).toBeFocused()
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
  expect(requested.every(url => url.endsWith('moment-03.mp4'))).toBe(true)
  expect(errors).toEqual([])
})

test('horizontal dragging moves cards without accidentally opening playback; vertical touch stays native', async ({ page, isMobile }) => {
  await load(page); await go(page, 0)
  const bounds = await page.getByRole('button', { name: 'Open The Peach Bowl' }).boundingBox()
  const x = bounds!.x + bounds!.width * .7, y = bounds!.y + bounds!.height * .5
  if (isMobile) {
    const session = await page.context().newCDPSession(page)
    await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
    for (let i = 1; i <= 12; i++) {
      await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - i * 16, y: y + 1 }] })
      await page.waitForTimeout(25)
    }
    await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await expect(host(page)).toHaveAttribute('data-dragging', 'false')
    await expect.poll(async () => Number(await host(page).getAttribute('data-position'))).toBeGreaterThan(.5)
    await page.waitForTimeout(600)
    const before = await page.evaluate(() => scrollY)
    await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 195, y: 500 }] })
    for (let i = 1; i <= 10; i++) {
      await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 196, y: 500 - i * 16 }] })
      await page.waitForTimeout(25)
    }
    await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await expect.poll(() => page.evaluate(() => scrollY)).toBeGreaterThan(before + 30)
    await session.detach()
  } else {
    await page.mouse.move(x, y); await page.mouse.down()
    await page.mouse.move(x - 300, y + 1, { steps: 15 })
    await expect(host(page)).toHaveAttribute('data-dragging', 'true')
    await page.mouse.up()
    await expect(host(page)).toHaveAttribute('data-dragging', 'false')
    await expect.poll(async () => Number(await host(page).getAttribute('data-position'))).toBeGreaterThan(.5)
  }
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('reduced motion removes spin and ambient float while keeping playback and navigation', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await load(page)
  await host(page).evaluate(el => window.scrollTo({ top: Number(el.dataset.entranceDistance) / 2, behavior: 'instant' }))
  await expect.poll(() => page.locator('.signature-flight').evaluate(el => el.style.getPropertyValue('--signature-spin'))).toBe('0deg')
  expect(await page.locator('.signature-float').first().evaluate(el => getComputedStyle(el).animationName)).toBe('none')
  await go(page, 2)
  await page.getByRole('button', { name: 'Open The Catch', exact: true }).click({ force: true })
  await playing(page)
  await page.keyboard.press('Escape')
  await expect(page.locator('video')).toHaveCount(0)
})

test('short and landscape phones retain readable cards and bounded players through orientation changes', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 650 })
  await load(page); await go(page, 2)
  const heading = await page.locator('.signature-heading').boundingBox(), card = await page.getByRole('button', { name: 'Open The Catch', exact: true }).boundingBox()
  expect(card!.y).toBeGreaterThan(heading!.y + heading!.height + 10)
  const caption = await page.locator('.signature-caption').nth(2).boundingBox(), nav = await page.locator('.signature-navigation').boundingBox()
  expect(caption!.y + caption!.height).toBeLessThan(nav!.y)
  await page.getByRole('button', { name: 'Open The Catch', exact: true }).click({ force: true })
  await playing(page)
  await page.setViewportSize({ width: 650, height: 390 })
  await expect(host(page)).toHaveAttribute('data-orientation', 'landscape')
  await page.waitForTimeout(850)
  const rect = await page.locator('video').boundingBox()
  expect(rect!.x).toBeGreaterThanOrEqual(0); expect(rect!.y).toBeGreaterThanOrEqual(0)
  expect(rect!.x + rect!.width).toBeLessThanOrEqual(651)
  expect(rect!.y + rect!.height).toBeLessThanOrEqual(391)
  await page.getByRole('button', { name: 'Close video' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(host(page)).toHaveAttribute('data-current', '2')
})

test('render scheduling rests when idle and hidden; media pauses on visibility changes', async ({ page }) => {
  await load(page); await go(page, 2)
  const renders = await host(page).getAttribute('data-render-count')
  await page.waitForTimeout(220)
  expect(await host(page).getAttribute('data-render-count')).toBe(renders)
  await page.getByRole('button', { name: 'Open The Catch', exact: true }).click({ force: true })
  await playing(page)
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: true }); document.dispatchEvent(new Event('visibilitychange')) })
  await expect(host(page)).toHaveAttribute('data-active', 'false')
  await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).paused)).toBe(true)
  const hiddenRenders = await host(page).getAttribute('data-render-count')
  await page.waitForTimeout(150)
  expect(await host(page).getAttribute('data-render-count')).toBe(hiddenRenders)
  await page.evaluate(() => { Reflect.deleteProperty(document, 'hidden'); document.dispatchEvent(new Event('visibilitychange')) })
  await playing(page)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.locator('.signature-demo-end').scrollIntoViewIfNeeded()
  await expect(host(page)).toHaveAttribute('data-active', 'false')
  expect(await page.locator('.signature-float').first().evaluate(el => { const css = getComputedStyle(el); return css.animationName === 'none' || css.animationPlayState === 'paused' })).toBe(true)
})

test('blocked audible autoplay falls back to muted playback and keeps a usable unmute control', async ({ page }) => {
  await page.addInitScript(() => {
    const play = HTMLMediaElement.prototype.play
    HTMLMediaElement.prototype.play = function () {
      return !this.muted ? Promise.reject(new DOMException('Gesture required', 'NotAllowedError')) : Reflect.apply(play, this, [])
    }
  })
  await load(page); await go(page, 2)
  await page.getByRole('button', { name: 'Open The Catch', exact: true }).click({ force: true })
  await playing(page)
  await expect(page.getByRole('button', { name: 'Unmute', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Unmute', exact: true }).click()
  await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).muted)).toBe(false)
  await page.keyboard.press('Escape')
})

test('video failures can retry, close, and reopen without leaving a scroll lock', async ({ page }) => {
  let fail = true
  await page.route('**/moment-03.mp4', route => fail ? route.abort() : route.continue())
  await load(page); await go(page, 2)
  await page.getByRole('button', { name: 'Open The Catch', exact: true }).click({ force: true })
  await expect(page.getByText('This video could not load.')).toBeVisible()
  fail = false
  await page.getByRole('button', { name: 'Retry video' }).click()
  await playing(page)
  await page.getByRole('button', { name: 'Close video' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Open The Catch', exact: true }).click({ force: true })
  await playing(page)
  await page.keyboard.press('Escape')
  await expect(page.locator('video')).toHaveCount(0)
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
})

test('gallery keeps the component lazy and scrolls its mobile iframe independently', async ({ page }) => {
  const requests: string[] = []
  page.on('request', request => { if (request.url().includes('/signature-moments/')) requests.push(request.url()) })
  await page.goto('/')
  await expect(page.frameLocator('iframe').getByRole('button', { name: 'Cream', exact: true })).toBeVisible()
  expect(requests).toEqual([])
  await page.getByRole('button', { name: 'Signature Moments', exact: false }).click()
  await page.getByRole('button', { name: 'Mobile', exact: true }).click()
  await page.locator('iframe').scrollIntoViewIfNeeded()
  const frame = page.frameLocator('iframe'), surface = frame.locator('.signature-moments')
  await expect(surface).toHaveAttribute('data-ready', 'true')
  await expect(surface).toHaveAttribute('data-layout', 'phone')
  const outerScroll = await page.evaluate(() => scrollY)
  await frame.getByRole('button', { name: 'Explore signature moments' }).click({ force: true })
  await expect(surface).toHaveAttribute('data-phase', 'moments')
  await frame.getByRole('button', { name: 'Show moment 3 of 5' }).click()
  await expect(surface).toHaveAttribute('data-current', '2')
  expect(await page.evaluate(() => scrollY)).toBe(outerScroll)
  await frame.getByRole('button', { name: 'Open The Catch', exact: true }).click({ force: true })
  await expect(frame.locator('video')).toHaveCount(1)
  await page.getByRole('button', { name: 'Leather Background', exact: false }).click()
  await expect(frame.getByRole('button', { name: 'Cream', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
})

test('custom content, imperative API, image-only cards and empty data work without the lab shell', async ({ page }) => {
  await page.goto('/tests/fixtures/signature-moments.html?static')
  await expect(page.locator('output').first()).toHaveText('1')
  await page.getByRole('button', { name: 'Go to second chapter' }).click()
  await expect(host(page)).toHaveAttribute('data-current', '1')
  await expect(page.getByRole('heading', { name: 'My chapters', exact: true })).toBeVisible()
  await expect(page.locator('output').nth(1)).toHaveText('1')
  await expect(page.locator('.signature-origin')).toHaveCount(0)
  expect(await host(page).evaluate(el => getComputedStyle(el).getPropertyValue('--signature-background'))).toBe('#102625')
  expect(await page.locator('.signature-card-plane').nth(1).evaluate(el => new DOMMatrixReadOnly(getComputedStyle(el).transform).isIdentity)).toBe(true)
  await page.getByRole('button', { name: 'Open first chapter', exact: true }).click()
  await playing(page)
  await page.keyboard.press('Escape')
  await expect(page.locator('video')).toHaveCount(0)
  await page.goto('/tests/fixtures/signature-moments.html?empty')
  await expect(page.getByText('No moments yet.')).toBeVisible()
  await expect(page.locator('output').first()).toHaveText('1')
  await page.getByRole('button', { name: 'Open first chapter', exact: true }).click()
  await expect(page.locator('video')).toHaveCount(0)
  await page.goto('/tests/fixtures/signature-moments.html?broken')
  await expect(host(page)).toHaveAttribute('data-ready', 'true')
  await expect(page.locator('.signature-card-plane').first()).toHaveAttribute('data-image-error', 'true')
  await expect(page.locator('.signature-image-fallback').first()).toBeVisible()
})

test('all five local clips play, and reopening releases the previous media element', async ({ page }) => {
  await load(page)
  for (let index = 0; index < 5; index++) {
    await go(page, index)
    await page.locator('.signature-card').nth(index).click({ force: true })
    await playing(page)
    await expect(page.locator('video')).toHaveCount(1)
    await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).videoWidth > 0 && (v as HTMLVideoElement).videoHeight > 0)).toBe(true)
    await expect(page.locator('.signature-player-mover')).toHaveAttribute('data-settled', 'true')
    expect(await page.locator('.signature-pin').evaluate(el => el.scrollLeft)).toBe(0)
    const bounds = await page.locator('video').boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width + 1)
    await page.getByRole('button', { name: 'Close video' }).click()
    await expect(page.locator('video')).toHaveCount(0)
  }
})

test('pointer sheen responds to hover; cancel, outside click, and scroll close cleanly', async ({ page, isMobile }, info) => {
  await load(page); await go(page, 2)
  if (!isMobile && info.project.name !== 'reduced-motion') {
    const plane = page.locator('.signature-card-plane').nth(2)
    const before = await plane.evaluate(el => getComputedStyle(el).transform)
    const bounds = await page.locator('.signature-card').nth(2).boundingBox()
    await page.mouse.move(bounds!.x + bounds!.width * .7, bounds!.y + bounds!.height * .3)
    await expect(host(page)).toHaveAttribute('data-watch', 'true')
    await expect.poll(() => plane.evaluate(el => getComputedStyle(el).transform)).not.toBe(before)
    await expect.poll(() => page.locator('.signature-sheen').nth(2).evaluate(el => Number(getComputedStyle(el).opacity))).toBeGreaterThan(.5)
    await page.screenshot({ path: 'artifacts/signature-validation/verified-hover.png' })
  }
  await page.getByRole('button', { name: 'Open The Catch', exact: true }).click({ force: true })
  await playing(page)
  await expect(page.locator('.signature-player-mover')).toHaveAttribute('data-settled', 'true')
  await page.locator('.signature-pin').click({ position: { x: 5, y: 180 }, force: true })
  await expect(page.locator('video')).toHaveCount(0)
  await page.getByRole('button', { name: 'Open The Catch', exact: true }).click({ force: true })
  await playing(page)
  await expect(page.locator('.signature-player-mover')).toHaveAttribute('data-settled', 'true')
  await page.mouse.move(5, 180)
  // Chromium mobile emulation converts CDP wheel deltas from device to CSS pixels.
  await page.mouse.wheel(0, 230 * await page.evaluate(() => devicePixelRatio))
  await expect(page.locator('video')).toHaveCount(0)
  const card = await page.locator('.signature-card').nth(2).boundingBox()
  await page.mouse.move(card!.x + 20, card!.y + 20); await page.mouse.down()
  await page.mouse.move(card!.x - 30, card!.y + 20, { steps: 4 })
  await expect(host(page)).toHaveAttribute('data-dragging', 'true')
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await expect(host(page)).toHaveAttribute('data-dragging', 'false')
  await page.mouse.up()
})
